# Generated by Django 4.2.2 on 2023-07-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='bgcolor_threshold',
            field=models.FloatField(default=''),
        ),
        migrations.AlterField(
            model_name='config',
            name='is_jpeg',
            field=models.BooleanField(default=True),
        ),
    ]
