# Generated by Django 4.2.2 on 2023-07-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_config_bgcolor_threshold_alter_config_is_jpeg'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='blurness_threshold',
            field=models.FloatField(default=50),
        ),
        migrations.AddField(
            model_name='config',
            name='pixelated_threshold',
            field=models.FloatField(default=20),
        ),
        migrations.AlterField(
            model_name='config',
            name='bgcolor_threshold',
            field=models.FloatField(default=50),
        ),
    ]
