# Generated by Django 4.2.2 on 2023-07-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_config_blurness_threshold_config_pixelated_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='greyness_threshold',
            field=models.FloatField(default=26),
        ),
    ]
