# Generated by Django 4.2.2 on 2023-07-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_config_symmetry_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='bypass_background_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='config',
            name='bypass_blurness_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='config',
            name='bypass_format_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='config',
            name='bypass_greyness_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='config',
            name='bypass_height_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='config',
            name='bypass_size_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='config',
            name='bypass_symmetry_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='config',
            name='bypass_width_check',
            field=models.BooleanField(default=False),
        ),
    ]
