# Generated by Django 4.2.2 on 2023-08-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_config_bypass_corrupted_check_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='blurness_threshold',
            field=models.FloatField(default=35),
        ),
        migrations.AlterField(
            model_name='config',
            name='greyness_threshold',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='config',
            name='pixelated_threshold',
            field=models.FloatField(default=50),
        ),
    ]
