# Generated by Django 4.2.4 on 2023-08-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_config_blurness_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='default_folder',
            field=models.BooleanField(default=False),
        ),
    ]
