# Generated by Django 4.2.4 on 2023-08-28 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_config_default_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='default_folder',
        ),
    ]
